# this is the configuration file for the the uid / gid checking utility.

excluded_users:
#  - root
  - daemon
  - bin
  - sys
  - sync
  - games
  - man
  - lp
  - mail
  - news
  - uucp
  - proxy
  - www-data
  - backup
  - list
  - irc
  - gnats
  - nobody
  - systemd-timesync
  - systemd-network
  - systemd-resolve
  - systemd-bus-proxy
  - syslog
  - _apt
  - lxd
  - messagebus
  - uuidd
  - dnsmasq
  - sshd
  - pollinate
